// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenAdoration.Infrastructure.Persistence;

#nullable disable

namespace OpenAdoration.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529000159_AddThemeHeaderFooter")]
    partial class AddThemeHeaderFooter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("OpenAdoration.Domain.Entities.BibleBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BibleVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Testament")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BibleVersionId", "BookNumber");

                    b.ToTable("BibleBooks");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.BibleVerse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BibleVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Verse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BibleVersionId", "Book", "Chapter");

                    b.HasIndex("BibleVersionId", "Book", "Chapter", "Verse")
                        .IsUnique();

                    b.ToTable("BibleVerses");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.BibleVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.ToTable("BibleVersions");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.HasIndex("ServiceId", "Order");

                    b.ToTable("ScheduleItems");

                    b.HasDiscriminator<string>("ItemType").HasValue("ScheduleItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerseOrder")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.SongSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SongId", "Order");

                    b.ToTable("SongSections");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImagePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundVideoPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FontColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FontSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FooterTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderTemplate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextAlignment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Center");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundColor = "#000000",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FontColor = "#FFFFFF",
                            FontFamily = "Arial",
                            FontSize = 48,
                            IsDefault = true,
                            Name = "Default",
                            TextAlignment = "Center",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.WorshipService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("WorshipServices");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.BibleScheduleItem", b =>
                {
                    b.HasBaseType("OpenAdoration.Domain.Entities.ScheduleItem");

                    b.Property<int?>("BibleVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerseEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerseStart")
                        .HasColumnType("INTEGER");

                    b.HasIndex("BibleVersionId");

                    b.HasDiscriminator().HasValue("Bible");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.MediaScheduleItem", b =>
                {
                    b.HasBaseType("OpenAdoration.Domain.Entities.ScheduleItem");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("MediaFileId");

                    b.HasDiscriminator().HasValue("Media");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.SongScheduleItem", b =>
                {
                    b.HasBaseType("OpenAdoration.Domain.Entities.ScheduleItem");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SongId");

                    b.HasDiscriminator().HasValue("Song");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.BibleBook", b =>
                {
                    b.HasOne("OpenAdoration.Domain.Entities.BibleVersion", "BibleVersion")
                        .WithMany("Books")
                        .HasForeignKey("BibleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleVersion");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.BibleVerse", b =>
                {
                    b.HasOne("OpenAdoration.Domain.Entities.BibleVersion", "BibleVersion")
                        .WithMany()
                        .HasForeignKey("BibleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleVersion");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.ScheduleItem", b =>
                {
                    b.HasOne("OpenAdoration.Domain.Entities.WorshipService", "Service")
                        .WithMany("Items")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenAdoration.Domain.Entities.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Service");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.SongSection", b =>
                {
                    b.HasOne("OpenAdoration.Domain.Entities.Song", "Song")
                        .WithMany("Sections")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.BibleScheduleItem", b =>
                {
                    b.HasOne("OpenAdoration.Domain.Entities.BibleVersion", "BibleVersion")
                        .WithMany()
                        .HasForeignKey("BibleVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BibleVersion");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.MediaScheduleItem", b =>
                {
                    b.HasOne("OpenAdoration.Domain.Entities.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.SongScheduleItem", b =>
                {
                    b.HasOne("OpenAdoration.Domain.Entities.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.BibleVersion", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.Song", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("OpenAdoration.Domain.Entities.WorshipService", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
