using OpenAdoration.Application.Common;

namespace OpenAdoration.Application.Services;

public interface IProjectionService
{
    /// <summary>The slide currently shown on the projector. Null when not projecting.</summary>
    Slide? CurrentSlide { get; }

    /// <summary>All slides loaded for the current schedule item.</summary>
    IReadOnlyList<Slide> CurrentSlides { get; }

    int CurrentSlideIndex { get; }
    bool IsProjecting { get; }

    /// <summary>Human-readable label for the item being projected (e.g. the song title). Empty when not projecting.</summary>
    string ContextLabel { get; }

    /// <summary>Fires whenever the displayed slide changes (including when projection stops).</summary>
    event EventHandler<Slide?> SlideChanged;

    /// <summary>Fires when projection starts or stops.</summary>
    event EventHandler<bool> ProjectionStateChanged;

    /// <summary>Fires when the active theme may have changed (e.g. theme was edited).</summary>
    event EventHandler? ThemeChanged;

    /// <summary>Loads a set of slides and immediately shows the first one.</summary>
    void LoadSlides(IReadOnlyList<Slide> slides, string contextLabel);

    void Next();
    void Previous();
    void GoTo(int index);

    /// <summary>Shows a blank (black) slide without stopping projection.</summary>
    void ShowBlank();

    /// <summary>
    /// Shows a free-text announcement as a banner overlay on top of the current slide,
    /// leaving the underlying slide untouched. No-op when not projecting.
    /// Replaces any banner already showing. Auto-dismiss timing is owned by the caller.
    /// </summary>
    void ShowAnnouncement(string text);

    /// <summary>Removes the announcement banner. The underlying slide is unaffected.</summary>
    void ClearAnnouncement();

    /// <summary>The current announcement banner text, or null when none is showing.</summary>
    string? CurrentAnnouncement { get; }

    /// <summary>True while an announcement banner is showing.</summary>
    bool IsAnnouncementActive { get; }

    /// <summary>Fires when <see cref="CurrentAnnouncement"/> changes (shown, replaced, or cleared).</summary>
    event EventHandler? AnnouncementChanged;

    /// <summary>Stops projection and clears state.</summary>
    void Stop();

    /// <summary>Notifies all subscribers that the active theme has been modified.</summary>
    void NotifyThemeChanged();

    /// <summary>Re-fires the current slide so subscribers re-render it (e.g., after a theme change).</summary>
    void RefreshCurrentSlide();

    /// <summary>
    /// Fires when the stage view asks the active service schedule to advance to the next schedule item.
    /// ServiceScheduleViewModel subscribes and handles it while in live mode.
    /// </summary>
    event EventHandler? NextScheduleItemRequested;

    /// <summary>Fires when the stage view asks the active service schedule to go back one schedule item.</summary>
    event EventHandler? PreviousScheduleItemRequested;

    /// <summary>Raises <see cref="NextScheduleItemRequested"/>.</summary>
    void RequestNextScheduleItem();

    /// <summary>Raises <see cref="PreviousScheduleItemRequested"/>.</summary>
    void RequestPreviousScheduleItem();

    /// <summary>True while a ServiceScheduleViewModel is running in live mode.</summary>
    bool IsServiceScheduleActive { get; }

    /// <summary>Fires when <see cref="IsServiceScheduleActive"/> changes.</summary>
    event EventHandler? ServiceScheduleActiveChanged;

    /// <summary>Called by ServiceScheduleViewModel when entering or exiting live mode.</summary>
    void SetServiceScheduleActive(bool active);

    /// <summary>
    /// The first slide of the next schedule item, pre-generated by ServiceScheduleViewModel
    /// so the stage view can preview it before the operator advances.
    /// Null when there is no next item or projection is not service-schedule-driven.
    /// </summary>
    Slide? NextScheduleItemPreviewSlide { get; }

    /// <summary>Fires when <see cref="NextScheduleItemPreviewSlide"/> changes.</summary>
    event EventHandler? NextScheduleItemPreviewChanged;

    /// <summary>Called by ServiceScheduleViewModel after loading each schedule item.</summary>
    void SetNextScheduleItemPreview(Slide? slide);
}
